export const permissions  = [
    {
      id: 1,
      name: "Create User",
      label: "USER_CREATE",
      code: "users.create",
      description: "Create a new user",
    },
    {
      id: 2,
      name: "Edit User",
      label: "EDIT_USER",
      code: "users.edit",
      description: "Edit existing user",
    },
    {
      id: 3,
      name: "Delete User",
      label: "DELETE_USER",
      code: "users.delete",
      description: "Delete user",
    },
    {
      id: 4,
      name: "View User",
      label: "USER_VIEW",
      code: "users.view",
      description: "View users details",
    },
    {
      id: 5,
      name: "Create Project",
      label: "PROJECT_CREATE",
      code: "projects.create",
      description: "Create new Projects",
    },
    {
      id: 6,
      name: "Edit Project",
      label: "PROJECT_EDIT",
      code: "projects.edit",
      description: "Edit existing project",
    },
    {
      id: 7,
      name: "Delete Project",
      label: "PROJECT_DELETE",
      code: "projects.delete",
      description: "Delete existing project",
    },
    {
      id: 8,
      name: "View Project",
      label: "PROJECTS_VIEW",
      code: "projects.view",
      description: "View project details",
    },
    {
      id: 9,
      name: "Create Leave",
      label: "LEAVE_CREATE",
      code: "Leaves.create",
      description: "Create new leaves",
    },
    {
      id: 10,
      name: "Edit Leave",
      label: "LEAVE_EDIT",
      code: "Leaves.edit",
      description: "Edit existing leave",
    },
    {
      id: 11,
      name: "Delete Leave",
      label: "LEAVE_DELETE",
      code: "Leaves.delete",
      description: "Delete existing leave",
    },
    {
      id: 12,
      name: "View Leave",
      label: "LEAVE_VIEW",
      code: "Leaves.view",
      description: "View leave details",
    },
  ];